permalink: /:year/:month/:day/:title/
disqus-shortname: kopisde
paginate: 5
# github default settings
markdown: rdiscount
safe: true
lsi: false
pygments: false
url: http://blog.kopis.de

# site settings
owner-name: Carsten Ringe
owner-email: carsten@kopis.de
owner-uri: http://www.kopis.de/

exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'style.scss', "Rakefile", "CNAME" ]
