site: KOPIS.DE
baseurl: /blog
url: https://www.kopis.de

collections:
  pages:
    output: true
    permalink: /blog/:name
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:slug
  projects:
    output: true
    permalink: /blog/project/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page:num/"
  
