# Site settings
title:       KOPIS.DE
email:       carsten@kopis.de
author:      Carsten Ringe
description: "Mein Blog über Software Entwicklung, Crossfit und andere Dinge"
baseurl:     '/blog'
# for feed urls
url:     "https://www.kopis.de"

# Google analytics
#google_analytics:

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: kopisde

# Social icons
show_social_icons: true
github_username: MoriTanosuke
stackoverflow_id: 834
twitter_username: carsten_r
google_plus_id: +CarstenRinge
linkedin_username:
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Diesen Artikel teilen'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
permalink:    pretty
paginate: 10
sass:
  compressed: true
