permalink: /:year/:month/:day/:title/
disqus-shortname: kopisde
paginate: 5
# github default settings
#markdown: rdiscount
safe: true
lsi: false
pygments: false

# site settings
owner-name: Carsten Ringe
owner-email: carsten@kopis.de

