#permalink: /:year/:month/:day/:title/
permalink: /:title/
disqus-shortname: kopisde
paginate: 15

# github default settings
markdown: rdiscount
safe: true
lsi: false
highlighter: 'pygments'
url: http://blog.kopis.de

gems:
  - jemoji

# site settings
owner-name: Carsten Ringe
owner-email: carsten@kopis.de
owner-uri: http://www.kopis.de/

exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'style.scss', "Rakefile", "CNAME", "Dockerfile" ]
