markdown: rdiscount
auto: true
paginate: 10

permalink: /:year/:month/:day/:title/

exclude: ["README.md", "LICENSE.md", "TODO.md", "build", "test", "CNAME", "_deploy.sh"]

owner-name: Carsten Ringe
owner-page: http://moritanosuke.github.com
owner-email: carsten@kopis.de
owner-title: Blog von Carsten Ringe

disqus-shortname: kopisde
url: http://blog.kopis.de/
feedburner: http://feeds.feedburner.com/kopisde

license: <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/"><img alt="Creative Commons Lizenzvertrag" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/88x31.png" /></a><br />Dieses Werk bzw. Inhalt steht unter einer <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/">Creative Commons Namensnennung-Nicht-kommerziell-Weitergabe unter gleichen Bedingungen 3.0 Unported Lizenz</a>.
